manifest:
  defaults:
    revision: main
  remotes:
    - name: karl5275
      url-base: https://github.com/karl5275
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: karl5275
      revision: AAbatteries-zephyr4
      import: app/west.yml
  self:
    path: config
